# This file is generated by Dist::Zilla::Plugin::CPANFile v6.030
# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.

requires "JSON::MaybeXS" => "1.004004";
requires "Moo" => "2.005005";
requires "Ref::Util" => "0.204";
requires "Sub::Exporter" => "0.987";
requires "Try::Tiny" => "0.31";
requires "Type::Tiny" => "2.002001";
requires "Unexpected" => "v1.0.8";
requires "namespace::autoclean" => "0.29";
requires "perl" => "5.010001";
requires "strictures" => "2.000006";

on 'build' => sub {
  requires "Module::Build" => "0.4004";
  requires "version" => "0.88";
};

on 'test' => sub {
  requires "File::Spec" => "0";
  requires "Module::Build" => "0.4004";
  requires "Module::Metadata" => "0";
  requires "Sys::Hostname" => "0";
  requires "Test::Requires" => "0.06";
  requires "version" => "0.88";
};

on 'test' => sub {
  recommends "CPAN::Meta" => "2.120900";
};

on 'configure' => sub {
  requires "Module::Build" => "0.4004";
  requires "version" => "0.88";
};
